### ISSUE TITLE
Make `Folder::$ignore` public

### ISSUE THREAD

**Issue by lukasbestle** [k-next/filesystem#2]
Maybe we should make the `$ignore` array public so that users can extend it with their own file ignores.

**Comment by bastianallgeier** [comment]
I tried to not have public attributes anymore if not really necessary. I would actually prefer to have a ignore method, which sets the array. That way we have a chance to validate the input.

**Comment by lukasbestle** [comment]
Makes a lot of sense. But then we should use this pattern everywhere in my opinion. I have seen another class in v3 that still uses the public attribute pattern (I don't know which one).

**Comment by bastianallgeier** [comment]
I already started replacing it wherever I still use it.

**Comment by lukasbestle** [comment]
Fantastic! 👍
