### ISSUE TITLE
Existence of F class

### ISSUE THREAD

**Issue by distantnative** [k-next/filesystem#5]
I started moving the old F toolkit class to FileSystem\File\F: https://github.com/k-next/filesystem/commit/0812efc65ee4b6a678f10e5ddc48e74c29102739

However, itself has a lot of dependencies. Among them also things like ZipArchive.

So there are a few questions:
- Do we want F to be part of the FileSystem package? Or have it also in v3 als Toolkit class?
- Do we want to have such an additional short name utility class with mostly static methods?
- Do we want to carry over methods like unzip etc.?

**Comment by bastianallgeier** [comment]
All very good questions. Right now I think I would prefer to port over all F methods, which make sense to the File class and have them object oriented. We could still think about creating a static interface for it later.
