### ISSUE TITLE
Reintroduce F::safeName sanitization in File::rename

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/filesystem#8]
I removed this entirely for now until we have an appropriate place where we can rebuild the F::safeName functionality outside of the toolkit.

**Comment by distantnative** [comment]
I suggested to introduce a `Toolkit\Value` class in https://github.com/k-next/toolkit/pull/12 (to find a place for the `size()` helper). Maybe that could also be a good place for a `safeName` method?
